### ISSUE TITLE
Uhm -_- Error

### ISSUE THREAD

**Issue by Faq** [CursedLand/Cursed.Reactor#1]
Got this error while running on this file: https://mega.nz/file/70VDWaLL#WGHD25PTusHTlPORb52qsx1oN0kaPQMd9hmSVRYn31E
![image](https://user-images.githubusercontent.com/322016/107847724-9559ba00-6df6-11eb-93e6-0f5dcbcee8e0.png)

**Comment by Kingmaker007-ui** [comment]
can give tool which you compile to check what's the problem...

**Comment by Faq** [comment]
There is provided link to exe file on what got the error, did you check it?

**Comment by Faq** [comment]
@CursedLand why closed?
